name: Product Catalog CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  SERVICE_DIR: src/product-catalog
  IMAGE_NAME: product-catalog-service

jobs:

####################################
# BUILD
####################################

  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/product-catalog

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - run: go mod download

      - run: go build -v .

      - run: go test ./...

####################################
# LINT
####################################

  lint:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/product-catalog

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - run: go mod download

      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2
          working-directory: src/product-catalog

####################################
# DOCKER
####################################

  docker:

    needs:
      - build
      
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./src/product-catalog
          file: ./src/product-catalog/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/product-catalog-service:${{ github.run_number }}
            ${{ secrets.DOCKER_USERNAME }}/product-catalog-service:latest

####################################
# DEPLOY
####################################

  deploy:

    needs: docker

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::900840136277:role/GitHub-OIDC-role
          aws-region: us-east-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name my-eks-cluster \
            --region us-east-1

      - name: Deploy
        run: |
          kubectl apply -f kubernetes/productcatalog/deploy.yaml
          kubectl apply -f kubernetes/productcatalog/svc.yaml